#'@title Unpack clusterProfiler GO Enrichment Results
#'
#'@name enrichgo_unpack_ver3
#'
#'@description
#' Unpacks the results of the ORA and outputs a nested list of Terms with their DEGs statistics.
#' Allows users the option to convert the ensemble IDs from clusterProfiler to their named gene-ids
#'@param initial_table_list
#' A list containing the filtered differential expression results for each
#' cluster or comparison. The tables should contain the gene identifiers and
#' differential expression statistics required to associate DEGs with enriched
#' GO terms.
#' @param key
#' A list of over-representation analysis results generated by
#' \code{clusterProfiler}, such as the output from
#' \code{\link[clusterProfiler]{enrichGO}}.
#'
#' @param pval_adj_threshold
#' Numeric value specifying the adjusted p-value threshold used to filter
#' enriched GO terms. Terms with adjusted p-values above this threshold are
#' excluded from the returned results.
#'
#' @param convert
#' Logical value indicating whether gene identifiers should be converted using
#' \code{\link{gene_id_converter_ver2}}. If \code{TRUE}, identifiers are
#' converted from \code{from_type} to \code{to_type}. If \code{FALSE}, the
#' original gene identifiers are retained.
#'
#' @param from_type
#' Character string specifying the original annotation type of the genes.
#' Supported values include \code{"ensembl"}, \code{"entrez"}, and
#' \code{"symbol"}.
#'
#' @param to_type
#' Character string specifying the desired annotation type of the genes.
#' Supported values include \code{"ensembl"}, \code{"entrez"}, and
#' \code{"symbol"}.
#'
#' @param org_db
#' An organism-specific annotation database used to facilitate gene identifier
#' conversion, such as \code{org.Hs.eg.db} for human or
#' \code{org.Mm.eg.db} for mouse.
#'
#' @param ensembl_dataset
#' Character string specifying the Ensembl dataset used for annotation.
#' For example, \code{"hsapiens_gene_ensembl"} for human genes.
#'
#' @importFrom tibble as_tibble tibble
#' @importFrom dplyr mutate filter inner_join relocate all_of
#' @importFrom biomaRt useMart getBM
#' @importFrom AnnotationDbi mapIds
#'
#'@details
#'For each clusterProfiler result for each comparison available within, extract the gene_ids, then join them with their edgeR differential expression results
#'
#'@references
#'Yu G, Wang LG, Han Y, He QY., OMICS May, 2012
#'
#'@export
enrichgo_unpack_ver3 <- function(
                      # Pass the whole list so we can grab comparisons
                      initial_table_list = filtered_results,
                      key = ora_output_down$enrichgo_results,
                      pval_adj_threshold = 0.001,

                      # Assume user does not want to convert geneids
                      convert = FALSE,
                      from_type = "ensembl",
                      to_type = "symbol",
                      org_db = org.Hs.eg.db,
                      ensembl_dataset = "hsapiens_gene_ensembl"){


  ### helper functionf or converting geneidA to geneidB
  ### user
  gene_id_converter_ver2 <- function(vector,
                                     from_type,
                                     to_type,
                                     org_db,
                                     ensembl_datset){

    # geneid pulling for correct attribute
    id_map <- c(
      ensembl = "ensembl_gene_id",
      entrez  = "entrezgene_id",
      symbol  = "external_gene_name"
    )
    # Pass the the ID mapping index over to the new attribute string
    from_attr <- id_map[[from_type]]
    to_attr <-id_map[[to_type]]

    #initialize the return and parameters
    #baseline NULL intialization
    return_df <- NULL
    max_attempts <- 2
    attempt <- 1
    org_db <- org.Hs.eg.db


    #Fix 1: There is a huge API crash almost 50% of the time that I use getBM() function to connect to the API
    #Implementing a while loop/tryCatch function to loop API calls just in case that the getBM work
    #Solution:After 10 attempts,

    #while the current attemp is less than or equal to the max attempts and while the return DF is null
    while(attempt <= max_attempts && is.null(return_df)){
      return_df <- tryCatch({

        message(sprintf("biomaRt attempt %d of %d...", attempt, max_attempts))

        #call the getBM ensemble API
        ensembl <- useMart(biomart = "ensembl", dataset = ensembl_dataset)
        getBM( attributes = c(from_attr, to_attr), filters = from_attr, values = vector, mart = ensembl)

        #If there is any kind of error
      }, error=function(e){
        #message for that error
        message(sprintf("  -> biomaRt attempt %d failed: %s", attempt, trimws(e$message)))
        #Return a NULL DF
        return(NULL)
      })

      # During that current attempt, If the return_df is still null
      if (is.null(return_df)) {
        # add on the attempt counter
        attempt <- attempt + 1
        # If the attempt counter is still less than the max attempts
        if (attempt <= max_attempts) {
          Sys.sleep(2) # Brief pause to prevent hammering the server
        }
      }# end of second if statement
    }#end of while loop

    if(is.null(return_df)){
      dbi_map <- c(
        ensembl = "ENSEMBL",
        entrez  = "ENTREZID",
        symbol  = "SYMBOL"
      )

      dbi_from <- dbi_map[[from_type]]
      dbi_to   <- dbi_map[[to_type]]

      return_df <- AnnotationDbi::mapIds(org_db,
                                         keys = vector,
                                         keytype = dbi_from,
                                         column =   dbi_to,
                                         multiVals = "first")

      return_df <- data.frame(
        from_attr = names(return_df),
        to_attr = unname(return_df))

      colnames(return_df) <- c(from_attr, to_attr)
    }
    return(return_df)
  }#end of whole function



  ###creates a helper function to unlist and strsplits the enriched Gene IDs per term
  unlist_converter <- function(str) {
    if (grepl("^ENSG|\\d", str)){
      bruh <- as.character(unlist(strsplit(str, "/")))
    }else{
      bruh <- as.integer(unlist(strsplit(str, "/")))
    }
    return(bruh)
  }


  # FIX 2: Corrected the spelling typo here
  unpacking_results <- list()

  # FIX 1: Loop over names(key) so 'comparison' is a valid character string identifier
  for (comparison in names(key)) {

    # Safeguard check: If the comparison doesn't exist in the clusterProfiler results, skip
    if (is.null(key[[comparison]])) next

    #for each comparison's key@result convert the Description (Term) column conver it to character result
    cluster <- tibble::as_tibble(key[[comparison]]@result) %>%
      dplyr::mutate(Description = as.character(Description))

    # if the user wants to grab the statistically signifcant results filter by the input
    if (!is.null(pval_adj_threshold)) {
      significant_clusters <- cluster %>%
        dplyr::filter(p.adjust < pval_adj_threshold)
    } else {
      significant_clusters <- cluster
    }

    labeled_gene_lists <- list()

    # FIX 3: Pull the specific comparison dataframe from your filtered results list
    current_initial_table <- initial_table_list[[comparison]] %>%
      dplyr::mutate(geneid = as.character(geneid))

    # If there are no significant clusters, jump to saving the empty list or next comparison
    if (nrow(significant_clusters) == 0) {
      unpacking_results[[comparison]] <- labeled_gene_lists
      next
    }
    # for each sgnicant cluster
    for (i in seq_len(nrow(significant_clusters))) {
      #grab the Description cluster

      go_term <- significant_clusters$Description[i]

      # Extract genes for current GO term
      genes <- unlist_converter(significant_clusters$geneID[i])

      #create a tibble with the go_term and the genes
      pathway_tibble <- tibble::tibble(
        gene_desc = rep(go_term, length(genes)),
        geneid = as.character(genes)
      )
    #
      if (convert == FALSE) {
        pathway_genenames <- pathway_tibble
      } else {
        pathway_genenames <- bulk_analysis::gene_id_converter_ver2(
          pathway_tibble$geneid,
          from_type = from_type,
          to_type = to_type,
          org_db = org_db,
          ensembl_dataset = ensembl_dataset
        )

        new_colname <- paste0(to_type, "_geneid")

        # FIX 4: Cleaner, bulletproof column renaming by position
        colnames(pathway_genenames)[1] <- "geneid"
        colnames(pathway_genenames)[2] <- new_colname
      }

      # Join converted names
      final_path_tibble <- dplyr::inner_join(pathway_tibble, pathway_genenames, by = "geneid") %>%
        dplyr::mutate(geneid = as.character(geneid))

      # Join fold changes / statistics using our dynamically updated initial table
      final_path_fc_tibble <- dplyr::inner_join(final_path_tibble, current_initial_table, by = "geneid")

      # Relocate converted gene_id column
      if (convert == TRUE) {
        fpfc_tibble <- final_path_fc_tibble %>%
          dplyr::relocate(dplyr::all_of(new_colname), .after = geneid)
      } else {
        fpfc_tibble <- final_path_fc_tibble
      }

      # Store result under the GO Term name
      labeled_gene_lists[[go_term]] <- fpfc_tibble
    }

    # Store the list of terms into the master list under the Comparison name
    unpacking_results[[comparison]] <- labeled_gene_lists
  }
  return(unpacking_results)
}
